### ISSUE TITLE
Question: What major mode do you use?

### ISSUE THREAD

**Issue by LoveSponge** [accidentalrebel/emacs-haxe-tools#1]
I see you say you have used emacs for haxe development for a while but i can't seem to find any working major mode for haxe at all!

If you'd be so kind as to point me in the right direction, i'd be extremely grateful.

Thanks

**Comment by accidentalrebel** [comment]
Hey there.

It's actually been years since I last coded with Haxe. I did use it a lot before and I used Haxe Mode found here:
https://github.com/emacsmirror/haxe-mode

It's very outdated and it took me a long time to get it running. It works but is woefully lacking in modern features which is why I made a number of haxe packages to make using it easier.

Hope this answer helps!
